In [65]:
#Approximating the L2 norm using neural network using keras and numpy 

import numpy as np
import tensorflow as tf
import keras


In [66]:
from keras.layers import Dense, Flatten, Dropout
from keras.models import Sequential


In [67]:
model = Sequential()

In [68]:
#building the neural network model
model.add(Dense (100, activation='relu',input_shape=(1,100)))
model.add(Dense(80,activation='relu'))
model.add(Dense(60,activation='relu'))
model.add(Dense(40,activation='relu'))
model.add(Dense(20,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(1,activation='relu'))

In [69]:
a=[2,3,1]
np.linalg.norm(a)

3.7416573867739413

In [70]:
b=[[2,3,1],[1,8,3],[6,2,4]]
np.linalg.norm(b,axis=1)

array([3.74165739, 8.60232527, 7.48331477])

In [71]:
#randomly generating the training data
y_train= x_train=np.random.rand(100000,1,100)*20-10
print(x_train[15])

[[-8.67506936  0.93559047  2.43728016 -0.18862088 -4.00699619 -3.15757402
  -3.83093041  1.17854069  4.64751787 -3.20683457  7.27025906 -6.78275788
  -2.17548844 -2.47027145 -4.91323356 -3.17008874 -4.64990582 -8.41319553
   6.80469518  0.63041783  3.87850441  1.00280048  8.27480223 -3.78819996
  -6.66631384  7.79314478 -4.83177525  6.63947899  1.66393883  7.22802272
   2.3258096  -1.85537265  8.81928603 -5.61253933  9.80976243  2.00560731
   6.41947493 -0.30923267 -0.16610733 -5.95360756 -5.15133558  4.7252358
  -6.02169882  1.30048347 -6.79216967  5.74840889 -8.10964611 -5.25931229
  -9.78564768 -4.04484109  2.05528601 -1.85458988 -5.91119018 -8.6683645
   2.06332517 -2.97275912 -2.61458987 -0.57483626 -5.83838673  3.87499539
  -0.35901395  7.26072198 -1.23326739 -8.51602655  9.94400348 -0.72709424
   0.98151778 -9.25075235  0.9843751  -6.95989601  8.89007971  3.46968257
  -0.40877521 -5.94733504 -9.8611637  -2.20380357 -5.86883646 -2.95273487
  -2.16886801 -9.36434188 -6.72584053 -2

In [72]:
print(x_train.shape)

(100000, 1, 100)


In [73]:
x_train.size

10000000

In [74]:
#making the training set suitable for vectors ranging from 1-100 dimensions

for i in range(100000):
    n=np.random.randint(1,101)
    x_train[i][0][n:100]=0

In [75]:
x_train[27]

array([[ 4.27204127,  7.83677014,  9.7775079 , -5.52248589,  4.54098398,
        -8.46809271,  7.51170919,  8.23233542, -4.04583509,  4.53771101,
         4.9184187 , -7.66559207, -4.32051378,  1.76264527, -8.54457109,
         3.33152789,  7.03726851, -9.25238622, -9.19344423,  6.30874876,
         4.43017033,  3.46423569,  3.86748315,  9.52279364, -2.69979197,
        -4.34958126,  6.35987776, -4.17675247,  4.21944299, -3.72694918,
         1.73691154, -6.24188287, -3.87106385, -6.32899269, -1.28731476,
        -2.22485837, -5.37014173,  8.56347484, -4.85743429,  3.64407789,
        -8.08241345,  6.77184806,  4.72584068,  2.00130674,  4.03793769,
        -7.95006322, -1.59764006,  0.73541464,  6.76294679, -5.61685617,
        -8.97853459,  2.24785385, -7.21136634, -8.77071126,  4.63522654,
        -4.44757032,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0. 

In [76]:
print(y_train.shape)

(100000, 1, 100)


In [77]:
model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_22 (Dense)             (None, 1, 100)            10100     
_________________________________________________________________
dense_23 (Dense)             (None, 1, 80)             8080      
_________________________________________________________________
dense_24 (Dense)             (None, 1, 60)             4860      
_________________________________________________________________
dense_25 (Dense)             (None, 1, 40)             2440      
_________________________________________________________________
dense_26 (Dense)             (None, 1, 20)             820       
_________________________________________________________________
dense_27 (Dense)             (None, 1, 10)             210       
_________________________________________________________________
dense_28 (Dense)             (None, 1, 1)              11        
Total para

In [78]:
y_train = np.linalg.norm(x_train,axis=2)
print(y_train.shape)

(100000, 1)


In [79]:
y_train = np.expand_dims(y_train,axis = 2)
print(y_train.shape)

(100000, 1, 1)


In [80]:
x_train[369]

array([[-3.97944227,  1.60202237,  7.21658859,  6.53874706,  3.70734944,
        -0.83382457, -7.61503582,  0.48992101, -1.70318974,  8.56015606,
         2.80230934, -2.40979511, -0.49516259, -0.10427175,  2.03672595,
        -7.83261364, -3.27723989, -6.39309407, -0.51417842, -3.93698971,
         9.18266519, -0.2947685 ,  8.20825287,  5.03263442, -3.52755755,
         6.85597872,  6.53702514,  0.40702449, -3.57236962, -5.17298727,
         7.22779583,  6.51449576, -9.92052576,  6.40524746, -4.89693622,
        -3.41677839,  7.12953624,  6.65355505,  6.10607581,  1.21148678,
        -1.85201513,  9.58953799,  9.84917947,  4.88581503, -6.19449162,
         3.69149353,  1.30298834, -2.93540989, -8.55212596,  3.08927734,
         7.25152005, -9.86896369,  4.3671696 ,  4.84723785,  4.77435729,
         8.68338847, -5.94861622,  9.64166031, -2.70566261,  2.57946048,
         1.69095168, -2.736743  ,  5.72137516,  2.18251945,  0.1684009 ,
         8.17476599, -8.62828175,  9.49007618, -5.4

In [81]:
y_train[12]

array([[34.98423386]])

In [82]:
model.compile(loss='mean_squared_error',optimizer='adam',metrics=['mse'])
model.fit(x_train,y_train,verbose=1,epochs=50,validation_split=0.3,batch_size=128)

Train on 70000 samples, validate on 30000 samples
Epoch 1/50
70000/70000 [==============================] - 2s 32us/step - loss: 63.2221 - mean_squared_error: 63.2221 - val_loss: 4.6695 - val_mean_squared_error: 4.6695
Epoch 2/50
70000/70000 [==============================] - 2s 25us/step - loss: 3.3855 - mean_squared_error: 3.3855 - val_loss: 2.8767 - val_mean_squared_error: 2.8767
Epoch 3/50
70000/70000 [==============================] - 2s 25us/step - loss: 2.1356 - mean_squared_error: 2.1356 - val_loss: 2.3848 - val_mean_squared_error: 2.3848
Epoch 4/50
70000/70000 [==============================] - 2s 25us/step - loss: 1.6234 - mean_squared_error: 1.6234 - val_loss: 2.1275 - val_mean_squared_error: 2.1275
Epoch 5/50
70000/70000 [==============================] - 2s 25us/step - loss: 1.3777 - mean_squared_error: 1.3777 - val_loss: 1.8099 - val_mean_squared_error: 1.8099
Epoch 6/50
70000/70000 [==============================] - 2s 25us/step - loss: 1.2379 - mean_squared_error: 1.237

70000/70000 [==============================] - 2s 27us/step - loss: 0.4936 - mean_squared_error: 0.4936 - val_loss: 1.1750 - val_mean_squared_error: 1.1750
Epoch 50/50
70000/70000 [==============================] - 2s 24us/step - loss: 0.4935 - mean_squared_error: 0.4935 - val_loss: 1.1794 - val_mean_squared_error: 1.1794


In [83]:
n,m= map(int,raw_input().split())

5 1


In [84]:
for i in range(m):
    test = []
    for j in range(0,n):
        test.append((raw_input()))
    for j in range(n,100):
        test.append(0)
    test = np.array(test)
    print(test.shape)
    test = np.expand_dims(test,axis = 1)
    print(test.shape)
    test = np.transpose(test)
    test = np.expand_dims(test,axis = 0)
    print(test.shape)
    res = model.predict(test)
    print (res)

1
2
3
4
5
(100,)
(100, 1)
(1, 1, 100)
[[[7.8059072]]]
